version: "3.9"
services:
  medicina:
    build:
      context: ./Backend/medicina
      dockerfile: Dockerfile.medicina
    ports:
      - "5010:5000"
    networks:
      - red-backend
  nutricion:
    build:
      context: ./Backend/nutricion
      dockerfile: Dockerfile.nutricion
    ports:
      - "5020:5000"
    networks:
      - red-backend
  usuario:
    build:
      context: ./Backend/usuario
      dockerfile: Dockerfile.usuario
    ports:
      - "5040:5000"
    networks:
      - red-backend
  # reporte:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.reporte
  #   ports:
  #     - "5050:5000"
  #   depends_on:
  #     - db
  #   networks:
  #     - red-backend
  # prediccion:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prediccion
  #   ports:
  #     - "5060:5000"
  #   depends_on:
  #     - db
  #   networks:
  #     - red-backend
  nginx:
    image: nginx:latest
    volumes:
      - ./Backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - usuario
      #- server2
    ports:
      - "5000:5000"
    networks:
      - red-backend
networks:
  #se crea la red "red-servidores" usando el driver de tipo "bridge"
  red-backend:
    driver: bridge